"""
Prints the resolved capslock_mode behavior matrix, in the shape of the design
doc tables (docs/design/capslock_mode_matrix.md section 6), generated by
driving the real keymapper against the real config region. Compare by eye or
paste back into the design doc when it changes. Not a test module.

Toshy/tests/modmap_matrix_report.py
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

from toshy_common.modifier_modes import CAPSLOCK_MODES

from tests.modmap_verifier_harness import (
    KBD_TYPES,
    build_namespace,
    resolve_cell,
)


__version__ = '20260714'


def print_matrix():
    ns, cnfg = build_namespace()
    short_modes = [mode.replace('caps_is_', '') for mode in CAPSLOCK_MODES]
    column_width = max(len(short) for short in short_modes) + 2

    for tracked_key in ('caps', 'lctrl'):
        key_label = ('Caps-position key' if tracked_key == 'caps'
                        else 'Physical Left Ctrl key')
        print(f'\n### What the {key_label} becomes\n')
        header_cells = ''.join(short.ljust(column_width) for short in short_modes)
        print(f'{"Kbd":11}{"Context":10}{header_cells}')
        print('-' * (21 + column_width * len(short_modes)))
        for kbd_type in KBD_TYPES:
            for app_context in ('GUI', 'Terminal', 'Remote'):
                row_cells = ''
                for mode in CAPSLOCK_MODES:
                    result = resolve_cell(ns, cnfg, mode, kbd_type, app_context)
                    row_cells += result[tracked_key].ljust(column_width)
                print(f'{kbd_type:11}{app_context:10}{row_cells}')


def main():
    print_matrix()
    return True


if __name__ == '__main__':
    main()

# End of file #
